import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import './globals.css';
import { Header } from '@/components/layout/header';
import { Footer } from '@/components/layout/footer';
import { cn } from 'lazy-cn';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ GeistSans.variable } ${ GeistMono.variable } scroll-smooth`}
    >
      <body className={cn(
        "h-full min-h-screen",
        "text-foreground bg-background",
      )}>
        <Header />
        <main className="contain-layout">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}

